# Generated by Django 2.1.5 on 2019-07-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_city_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='img',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
